## comparison of the different sites 

```{r start}
## code for calculating site characteristics
## first read in all data:

library(plyr)
library(reshape2)
library(ggplot2)
source("../Rscripts/all_sites_parameters.R")

```

```{r }
sites <- c("Cardoso","Colombia","CostaRica","FrenchGuiana","Macae","Argentina")

all_schedules <- lapply(sites,scheduleread)
names(x=all_schedules) <- sites

## standardize names
all_schedules_renamed <- lapply(all_schedules,function(df){
  names(df)[1:4] <- c("trt.name","mu","k","temporal.block")
  df
  })

allsites <- ldply(.data=all_schedules_renamed,.fun=melt,id.vars=c("trt.name","mu","k","temporal.block"))
names(allsites)[names(allsites)==".id"] <- "site"

```


```{r preliminary graph}
#ggplot(allsites,aes(x=site,y=mu))+geom_point()
#ggplot(allsites,aes(x=site,y=k))+geom_point()
ggplot(subset(allsites,subset=allsites$trt.name=="mu1k1"),aes(x=mu,y=k,colour=site))+geom_point(size=3)

trtcols <- dcast(data=allsites,formula=site+temporal.block+variable~trt.name,value.var="value")


```


```{r clean}
head(allsites)
unique(allsites$variable)
allsites$Day <- as.numeric(gsub(allsites$variable,pattern="[a-zA-Z]+\\.?",replacement=""))
ggplot(allsites,aes(x=Day,y=value,group=trt.name))+geom_path()+facet_wrap(~site)

## remove the temporal block days:
# 
# tmpblock_sites <- split(allsites,allsites$temporal.block)
# 
# no_extra_days <- rbind(tmpblock_sites$a[!tmpblock_sites$a$Day%in%c(1:2,63:68),],
#                        tmpblock_sites$b[!tmpblock_sites$b$Day%in%c(1:3,64:68),],
#                        tmpblock_sites$c[!tmpblock_sites$c$Day%in%c(1:4,65:68),])
# 
# no_extra_days[which(is.na(no_extra_days$value)),]
#ggplot(allsites,aes(x=Day,y=value,group=trt.name))+geom_path()+facet_grid(~mu)

allsites_noNA <- allsites[!is.na(allsites$value),]

#ddply(allsites_noNA,.variables=.(sites),summarize,m)
```

```{r}

summary_sites <- ddply(allsites_noNA,.variables=.(site,trt.name),.fun=summarize,
                       maxrain=max(value),
                       drydays=sum(value==0)
                       )

```

```{r graph summaries}
ggplot(summary_sites,aes(x=drydays,colour=site))+geom_density()+xlab("number of dry days")
```
